FROM golang:alpine AS builder
WORKDIR /www/webapp
COPY . /www/webapp
RUN CGO_ENABLED=0 go build -o ./server/server ./server

FROM alpine AS runner
WORKDIR /www/webapp
COPY --from=builder /www/webapp/server/server .
EXPOSE 8001
CMD ["./server"]